[package]
name = "WebApp"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-files = "0.6.0"
actix-web = "4.0.0"
awc = "3.0.0"
dotenv = "0.15.0"
serde = { version = "1.0.132", features = ["derive"] }
serde_json = "1.0.79"
tera = "1.15.0"